@api = http://localhost:8000/api/tasks

###
GET {{api}}
Authorization: tokenX
###
GET {{api}}/6
###
POST {{api}}
Content-Type: application/json

{
    "title": "Task",
    "description": "Description"
}
###
DELETE {{api}}/8
###
PUT {{api}}/6
Content-Type: application/json

{
    "title": "TASK 6",
    "description": "DESCRIPTION 6"
}